const LOAD_FILE_LOAD_SOURCE = {
  USER: 'user',
  DEFAULT: 'default'
};

const LOAD_FILE_LOAD_STRATEGY = {
  DEFAULT_ONLY: 'DEFAULT_ONLY',
  USER_ONLY: 'USER_ONLY',
  USER_FIRST: 'USER_FIRST'
};

const LOAD_FILE_ISSUE_CODE = {
  PATH_MISSING: 'PATH_MISSING',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INVALID_JSON: 'INVALID_JSON',
  EMPTY_FILE: 'EMPTY_FILE',
  EMPTY_OBJECT: 'EMPTY_OBJECT',
  FATAL_LOAD: 'FATAL_LOAD',

  USER_PATH_MISSING: 'USER_PATH_MISSING',
  USER_FILE_NOT_FOUND: 'USER_FILE_NOT_FOUND',
  USER_INVALID_JSON: 'USER_INVALID_JSON',
  USER_EMPTY_FILE: 'USER_EMPTY_FILE',
  USER_EMPTY_OBJECT: 'USER_EMPTY_OBJECT',
  USER_FATAL_LOAD: 'USER_FATAL_LOAD',

  DEFAULT_PATH_MISSING: 'DEFAULT_PATH_MISSING',
  DEFAULT_FILE_NOT_FOUND: 'DEFAULT_FILE_NOT_FOUND',
  DEFAULT_INVALID_JSON: 'DEFAULT_INVALID_JSON',
  DEFAULT_EMPTY_FILE: 'DEFAULT_EMPTY_FILE',
  DEFAULT_EMPTY_OBJECT: 'DEFAULT_EMPTY_OBJECT',
  DEFAULT_FATAL_LOAD: 'DEFAULT_FATAL_LOAD',

  MISSING_ARGUMENTS: 'MISSING_ARGUMENTS',
  INVALID_STRATEGY: 'INVALID_STRATEGY',
  DUPLICATE_PATHS: 'DUPLICATE_PATHS'
};

const LOAD_FILE_ISSUE_MESSAGE = {
  PATH_MISSING: '{source} settings path is missing',
  FILE_NOT_FOUND: '{source} settings file not found',
  INVALID_JSON: '{source} settings file contains an invalid JSON',
  EMPTY_FILE: '{source} settings file is empty',
  EMPTY_OBJECT: '{source} settings file is empty object',
  FATAL_LOAD: 'Failed to load mandatory file',
  MISSING_ARGUMENTS: 'Missing required arguments',
  INVALID_STRATEGY: 'Invalid load strategy',
  DUPLICATE_PATHS: 'User and default paths are identical'
};


module.exports = {
  LOAD_FILE_LOAD_SOURCE,
  LOAD_FILE_LOAD_STRATEGY,
  LOAD_FILE_ISSUE_CODE,
  LOAD_FILE_ISSUE_MESSAGE
}
